#version 430
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform layout(set = 0, binding = 0, r32f) image2D heightMap;

void main() {
  
  ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
  
  vec4 result;
  result.x = sin(float(coords.x) * 0.05);
  
  imageStore(heightMap, coords, result);
  
  
}
