#version 430
#extension GL_GOOGLE_include_directive : enable
#include "../util/noise.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform layout(set = 0, binding = 0, r32f) image2D heightMap;

const float gridSize = 63.0;

void main() {
  
  ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
  vec2 uv = coords / gridSize;
  
  vec4 result;
  result.x = octNoise(uv * 5.0, 3);
  
  imageStore(heightMap, coords, result);
  
  
}
